version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DRUPAL_VERSION: V8
    steps:
      - checkout
      - run:
          name: "Setup variables"
          command: |
            echo $CIRCLE_BRANCH
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone --single-branch --depth 1 https://github.com/GetDKAN/dkan-tools.git
            chmod 777 ./dkan-tools/bin/dktl
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
      - run:
          name: Initialize Project
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            mkdir ~/sandbox
            cd ~/sandbox
            dktl init
            mv ~/project ./src/frontend
      - run:
          name: Get Drupal
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl get 8.8.5
      - run:
          name: Make DKAN
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl make --frontend=$CIRCLE_BRANCH
      - run:
          name: Install site
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl install
      - run:
          name: Run cypress tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl drush user:create testuser --password="2jqzOAnXS9mmcLasy"
            dktl drush en dkan_dummy_content dkan_frontend -y
            dktl drush dkan-dummy-content:create
            dktl drush queue:run dkan_datastore_import
            dktl drush en dkan_frontend
            dktl drush dkan-search:rebuild-tracker
            dktl drush search-api-index

            dktl dc exec web chmod -R 777 /var/www/docroot/data-catalog-frontend
            dktl dc run cli git clone --single-branch -b resource-update https://github.com/GetDKAN/data-catalog-components.git
            dktl dc run cli npm install --prefix /var/www/data-catalog-components --unsafe-perm
            dktl dc run -w /var/www/data-catalog-components cli npm pack --unsafe-perm
            dktl dc run -w /var/www/docroot/data-catalog-frontend cli npm install ../../data-catalog-components/civicactions-data-catalog-components-1.0.0.tgz
            dktl dc run cli cat /var/www/docroot/data-catalog-frontend/package.json
            dktl dc run -w /var/www/docroot/data-catalog-frontend cli rm -rf node_modules
            dktl dc run -w /var/www/docroot/data-catalog-frontend cli rm package-lock.json 
            dktl dc exec cli npm install --prefix /var/www/docroot/data-catalog-frontend --unsafe-perm
            dktl dc run cli cat /var/www/docroot/data-catalog-frontend/node_modules/@civicactions/data-catalog-components/package.json

            dktl frontend:build
            dktl dc exec web chmod -R 777 /var/www/docroot/sites/default/files/dkan-tmp
            dktl drush cr
            dktl dkan:test-cypress frontend
      - store_artifacts:
          path: ~/sandbox/src/frontend/cypress/screenshots
      - store_artifacts:
          path: ~/sandbox/src/frontend/cypress/videos
